pipeline:
  install:
    image: starefossen/ruby-node
    commands:
      - node -v
      - npm -v
      - npm install
      # - gem install timetrap
      # - timetrap d
      # - npm run test

  testing:
    image: starefossen/ruby-node
    commands:
      # - node -v
      # - npm -v
      # - npm install
      - gem install timetrap
      - timetrap d
      - npm run test
